<#macro inc_x><#assign x=x+1></#macro>
<#macro delta y_index><@inc_x/>"=IF(OR(ISBLANK(${(x-2)?upper_abc}${(yOff + y_index)?c}),ISBLANK(${(x-1)?upper_abc}${(yOff + y_index)?c})),"""",${(x-1)?upper_abc}${(yOff + y_index)?c}-${(x-2)?upper_abc}${(yOff + y_index)?c})"</#macro>
<#macro ratio_safe y_index divisor_offset><@inc_x/>"=IF(0<${(x-divisor_offset)?upper_abc}${(yOff + y_index)?c},${(x-1)?upper_abc}${(yOff + y_index)?c}/${(x-divisor_offset)?upper_abc}${(yOff + y_index)?c},"""")"</#macro>
<#macro project_sample y_index sample><#if sample?has_content>"=${sample?c}*(100/${sxy})"</#if></#macro>
<#macro inc_prj_smpl   y_index sample><@inc_x/><@project_sample y_index sample/></#macro>
<#macro twitter_followers_headers>"Followers"			</#macro>
<#macro twitter_followers_subheaders><@inc_x/>"Begin"	<@inc_x/>"End"	<@inc_x/>"Delta"	<@inc_x/>"Growth"</#macro>
<#macro twitter_followers timePeriodConceptReport y_index><@inc_x/>${(timePeriodConceptReport.beginFollowers?c)!}	<@inc_x/>${(timePeriodConceptReport.endFollowers?c)!}	<@delta y_index/>	<@ratio_safe y_index 3/></#macro>
<#macro expensive_stats_headers topics>"Sentiment (Adorescore)"			"Mentions"				<#list topics as topic>	"${topic}"		</#list>	"Outbound"	<#if topics?has_content>"Outbound on topic"<#list topics as topic>	</#list></#if>"Replies"					"Retweets"</#macro>
<#macro expensive_stats_subheaders topics><@inc_x/>"Begin"	<@inc_x/>"End"	<@inc_x/>"Delta"	<@inc_x/>"Total Mentions"	<@inc_x/>"Positive Mentions (Adored)"	<@inc_x/>"Positive mention engagement ratio"	<@inc_x/>"Negative Mentions (Floored)"	<@inc_x/>"Negative mention engagement ratio"<#list topics as topic>	<@inc_x/>"Tot"	<@inc_x/>"Pos"	<@inc_x/>"Neg"</#list>	<@inc_x/>"Outbound Statuses"<#list topics as topic>	<@inc_x/>"${topic}"</#list>	<@inc_x/>"Total Replies"	<@inc_x/>"Positive Replies"	<@inc_x/>"Positive Reply engagement ratio"	<@inc_x/>"Negative Replies"	<@inc_x/>"Negative Reply engagement ratio"	<@inc_x/>"Total Retweets"</#macro>
<#macro expensive_stats timePeriodConceptReport y_index topics><@inc_x/>${(timePeriodConceptReport.beginAdoreScore?c)!}	<@inc_x/>${(timePeriodConceptReport.endAdoreScore?c)!}	<@delta y_index/>	<@inc_prj_smpl y_index timePeriodConceptReport.totalMentions/>	<@inc_prj_smpl y_index timePeriodConceptReport.adored/>	<@ratio_safe y_index 2/>	<@inc_prj_smpl y_index timePeriodConceptReport.floored/>	<@ratio_safe y_index 4/><#list topics as topic><#assign is_topic = timePeriodConceptReport.topicalMentions?? && timePeriodConceptReport.topicalMentions[topic]??>	<@inc_x/><#if is_topic><@project_sample y_index timePeriodConceptReport.topicalMentions[topic].total!/></#if>	<@inc_x/><#if is_topic><@project_sample y_index timePeriodConceptReport.topicalMentions[topic].positive!/></#if>	<@inc_x/><#if is_topic><@project_sample y_index timePeriodConceptReport.topicalMentions[topic].negative!/></#if></#list>	<@inc_prj_smpl y_index timePeriodConceptReport.outboundStatuses!/><#list topics as topic>	<@inc_x/><#if timePeriodConceptReport.outboundTopics??><@project_sample y_index timePeriodConceptReport.outboundTopics[topic]!/></#if></#list>	<@inc_prj_smpl y_index timePeriodConceptReport.totalReplies!/>	<@inc_prj_smpl y_index timePeriodConceptReport.positiveReplies!/>	<@ratio_safe y_index 2/>	<@inc_prj_smpl y_index timePeriodConceptReport.negativeReplies!/>	<@ratio_safe y_index 4/>	<@inc_prj_smpl y_index timePeriodConceptReport.retweets!/></#macro>